// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk8tw7smD0sFPGVF0eAFTuBKExazznYBY',
    appId: '1:810676257968:web:c1f53b77569bf900d8a775',
    messagingSenderId: '810676257968',
    projectId: 'auht-fire-base',
    authDomain: 'auht-fire-base.firebaseapp.com',
    storageBucket: 'auht-fire-base.appspot.com',
    measurementId: 'G-WWN08Y6592',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7Myv6RH6JCwK6_30mfesUQN6MXMLWAEc',
    appId: '1:810676257968:android:0c929fca95144df5d8a775',
    messagingSenderId: '810676257968',
    projectId: 'auht-fire-base',
    storageBucket: 'auht-fire-base.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO5dcoNcuSyq7S6LceM-8xcakyFyP-ucA',
    appId: '1:810676257968:ios:b1b11f736e54bd14d8a775',
    messagingSenderId: '810676257968',
    projectId: 'auht-fire-base',
    storageBucket: 'auht-fire-base.appspot.com',
    iosBundleId: 'com.example.autenticacionFirebaseFlutter',
  );
}
